version: 2
defaults: &defaults
    machine:
      image: circleci/classic:edge
    steps:
      - run:
          name: Check docker is running
          command: docker info
      - run:
          name: Pull Community Hass.io Add-ons build environment
          command: docker pull hassioaddons/build-env:latest
      - run:
          name: Log in to Docker Hub
          command: |
            if [[ "${CIRCLE_BRANCH}" = "master" || ! -z "${CIRCLE_TAG:-}" ]];
            then
              docker login -u "${DOCKER_LOGIN}" -p "${DOCKER_PASSWORD}"
            fi
      - checkout
      - deploy:
          name: Build and (maybe) deploy
          command: |
              if [[ "${CIRCLE_BRANCH}" = "master" || ! -z "${CIRCLE_TAG:-}" ]];
              then
                docker run \
                  --privileged \
                  -v ~/.docker:/root/.docker \
                  -v "$PWD":/docker \
                  hassioaddons/build-env:latest \
                  --image "hassioaddons/ssh-{arch}" \
                  --git \
                  --target ssh \
                  --${ARCH} \
                  --push
              else
                docker run \
                  --privileged \
                  -v "$PWD":/docker \
                  hassioaddons/build-env:latest \
                  --image "hassioaddons/ssh-{arch}" \
                  --git \
                  --target ssh \
                  --${ARCH}
              fi

jobs:
  aarch64:
    <<: *defaults
    environment:
      ARCH: aarch64
  amd64:
    <<: *defaults
    environment:
      ARCH: amd64
  armhf:
    <<: *defaults
    environment:
      ARCH: armhf
  i386:
    <<: *defaults
    environment:
      ARCH: i386

workflows:
  version: 2
  build_and_maybe_deploy:
    jobs:
      - aarch64:
          filters:
            tags:
              only: /.*/
      - amd64:
          filters:
            tags:
              only: /.*/
      - armhf:
          filters:
            tags:
              only: /.*/
      - i386:
          filters:
            tags:
              only: /.*/